services:
  - type: web
    name: stegochain-backend
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 2 --timeout 120 --bind 0.0.0.0:$PORT 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
