"""
Web3.py Blockchain Client
==========================
Provides all Python-side interaction with the deployed StegoChain smart
contract running on a local Ganache / Hardhat network.

ABI loading priority:
    1. blockchain/artifacts/deployment.json  (generated by deploy.js)
    2. Hardcoded MINIMAL_ABI constant        (fallback when not yet deployed)

All signing uses web3.eth.account.sign_transaction so no unlocked node
account is required.  The caller supplies the raw private key.

Dependencies: web3 (already in requirements.txt)
"""

import hashlib
import json
import os

from web3 import Web3
from web3.exceptions import ContractLogicError


# ── ABI fallback ──────────────────────────────────────────────────────────────
# Minimal ABI covering every function used by this client.
# Replaced at runtime by the full ABI from deployment.json when available.
MINIMAL_ABI = [
    {
        "inputs": [],
        "stateMutability": "nonpayable",
        "type": "constructor"
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "name": "recordId",   "type": "uint256"},
            {"indexed": False, "name": "cid",         "type": "string"},
            {"indexed": True,  "name": "sender",      "type": "address"},
            {"indexed": True,  "name": "receiver",    "type": "address"},
            {"indexed": False, "name": "sessionId",   "type": "string"},
            {"indexed": False, "name": "merkleRoot",  "type": "bytes32"},
            {"indexed": False, "name": "timestamp",   "type": "uint256"}
        ],
        "name": "RecordRegistered",
        "type": "event"
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "name": "recordId",  "type": "uint256"},
            {"indexed": True,  "name": "revokedBy", "type": "address"},
            {"indexed": False, "name": "timestamp",  "type": "uint256"}
        ],
        "name": "RecordRevoked",
        "type": "event"
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "name": "recordId",     "type": "uint256"},
            {"indexed": False, "name": "newMerkleRoot", "type": "bytes32"},
            {"indexed": False, "name": "timestamp",     "type": "uint256"}
        ],
        "name": "MerkleRootUpdated",
        "type": "event"
    },
    {
        "inputs": [
            {"name": "cid",        "type": "string"},
            {"name": "receiver",   "type": "address"},
            {"name": "sessionId",  "type": "string"},
            {"name": "merkleRoot", "type": "bytes32"}
        ],
        "name": "registerRecord",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [{"name": "recordId", "type": "uint256"}],
        "name": "getRecord",
        "outputs": [
            {
                "components": [
                    {"name": "recordId",   "type": "uint256"},
                    {"name": "cid",        "type": "string"},
                    {"name": "sender",     "type": "address"},
                    {"name": "receiver",   "type": "address"},
                    {"name": "sessionId",  "type": "string"},
                    {"name": "merkleRoot", "type": "bytes32"},
                    {"name": "timestamp",  "type": "uint256"},
                    {"name": "isActive",   "type": "bool"}
                ],
                "name": "",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [{"name": "cid", "type": "string"}],
        "name": "getRecordByCID",
        "outputs": [
            {
                "components": [
                    {"name": "recordId",   "type": "uint256"},
                    {"name": "cid",        "type": "string"},
                    {"name": "sender",     "type": "address"},
                    {"name": "receiver",   "type": "address"},
                    {"name": "sessionId",  "type": "string"},
                    {"name": "merkleRoot", "type": "bytes32"},
                    {"name": "timestamp",  "type": "uint256"},
                    {"name": "isActive",   "type": "bool"}
                ],
                "name": "",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [{"name": "sender", "type": "address"}],
        "name": "getSenderRecords",
        "outputs": [{"name": "", "type": "uint256[]"}],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {"name": "recordId",   "type": "uint256"},
            {"name": "cid",        "type": "string"},
            {"name": "merkleRoot", "type": "bytes32"}
        ],
        "name": "verifyRecord",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {"name": "recordId",     "type": "uint256"},
            {"name": "newMerkleRoot","type": "bytes32"}
        ],
        "name": "updateMerkleRoot",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [{"name": "recordId", "type": "uint256"}],
        "name": "revokeRecord",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [
            {"name": "proof", "type": "bytes32[]"},
            {"name": "root",  "type": "bytes32"},
            {"name": "leaf",  "type": "bytes32"}
        ],
        "name": "verifyMerkleProof",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "pure",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "getContractStats",
        "outputs": [
            {"name": "totalRecords",   "type": "uint256"},
            {"name": "contractOwner",  "type": "address"}
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "recordCount",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function"
    }
]


# ── ABI loader ────────────────────────────────────────────────────────────────

def _load_abi() -> list:
    """
    Load ABI from blockchain/artifacts/deployment.json if it exists,
    otherwise fall back to the hardcoded MINIMAL_ABI.
    """
    # Walk up from this file's location to find the blockchain/artifacts dir
    this_dir      = os.path.dirname(os.path.abspath(__file__))
    deployment_path = os.path.normpath(
        os.path.join(this_dir, "..", "..", "..", "blockchain", "artifacts", "deployment.json")
    )
    if os.path.exists(deployment_path):
        with open(deployment_path, "r") as fh:
            data = json.load(fh)
        if "abi" in data and data["abi"]:
            return data["abi"]
    return MINIMAL_ABI


# ── Public API ────────────────────────────────────────────────────────────────

def get_web3_connection(ganache_url: str) -> Web3:
    """
    Create and return a Web3 instance connected to *ganache_url*.

    Raises
    ------
    ConnectionError : if the node is unreachable
    """
    w3 = Web3(Web3.HTTPProvider(ganache_url))
    if not w3.is_connected():
        raise ConnectionError(f"Cannot connect to Ethereum node at {ganache_url}")
    return w3


def load_contract(w3: Web3, contract_address: str, abi: list):
    """
    Return a Web3 contract instance.

    Parameters
    ----------
    w3               : connected Web3 instance
    contract_address : Ethereum address of the deployed contract
    abi              : contract ABI list

    Raises
    ------
    ValueError : if the address is not a valid Ethereum address
    """
    try:
        checksum_addr = Web3.to_checksum_address(contract_address)
    except Exception as exc:
        raise ValueError(f"Invalid contract address: {contract_address!r}") from exc

    return w3.eth.contract(address=checksum_addr, abi=abi)


def build_merkle_tree(cids: list) -> dict:
    """
    Build a Merkle tree from a list of IPFS CID strings.

    Each leaf is keccak256 of the UTF-8 encoded CID.
    Pairs at each level are sorted (smaller first) before hashing,
    matching the Solidity verifyMerkleProof implementation.
    If the number of nodes at any level is odd, the last node is duplicated.

    Parameters
    ----------
    cids : list of CID strings

    Returns
    -------
    dict:
        root   (str)        : 0x-prefixed bytes32 hex string of Merkle root
        leaves (list[str])  : hex strings of leaf hashes
        tree   (list[list]) : full tree, level 0 = leaves, last level = [root]
    """
    if not cids:
        raise ValueError("cids list cannot be empty")

    # Compute leaves
    leaves = [_keccak256_bytes(cid.encode("utf-8")) for cid in cids]
    tree   = [leaves[:]]   # level 0

    current = leaves[:]
    while len(current) > 1:
        if len(current) % 2 == 1:
            current.append(current[-1])   # duplicate last leaf
        next_level = []
        for i in range(0, len(current), 2):
            next_level.append(_hash_pair(current[i], current[i + 1]))
        current = next_level
        tree.append(current[:])

    root = "0x" + current[0].hex()
    return {
        "root":   root,
        "leaves": ["0x" + lf.hex() for lf in leaves],
        "tree":   [["0x" + n.hex() for n in level] for level in tree],
    }


def get_merkle_proof(cids: list, target_cid: str) -> list:
    """
    Compute the Merkle inclusion proof for *target_cid* in the tree built
    from *cids*.

    Parameters
    ----------
    cids       : same list used when building the tree
    target_cid : the CID whose inclusion should be provable

    Returns
    -------
    list of 0x-prefixed hex strings (sibling hashes, leaf to root)

    Raises
    ------
    ValueError : if target_cid is not in cids
    """
    if target_cid not in cids:
        raise ValueError(f"target_cid {target_cid!r} not found in cids list")

    raw_leaves = [_keccak256_bytes(c.encode("utf-8")) for c in cids]
    idx        = cids.index(target_cid)
    proof      = []

    current = raw_leaves[:]
    while len(current) > 1:
        if len(current) % 2 == 1:
            current.append(current[-1])

        next_level = []
        for i in range(0, len(current), 2):
            if i == idx - (idx % 2):          # this pair contains our node
                sibling_i = i + 1 if idx % 2 == 0 else i
                proof.append("0x" + current[sibling_i].hex())
            next_level.append(_hash_pair(current[i], current[i + 1]))

        idx    = idx // 2
        current = next_level

    return proof


def register_record(
    w3: Web3,
    contract,
    private_key: str,
    cid: str,
    receiver_address: str,
    session_id: str,
    merkle_root: str,
) -> dict:
    """
    Sign and send a registerRecord transaction.

    Parameters
    ----------
    w3               : connected Web3 instance
    contract         : loaded contract object
    private_key      : hex private key of the sender (with or without 0x prefix)
    cid              : IPFS CID to register
    receiver_address : Ethereum address of receiver
    session_id       : session identifier
    merkle_root      : 0x-prefixed bytes32 hex string

    Returns
    -------
    dict: { tx_hash, record_id, block_number, gas_used }
    """
    account          = w3.eth.account.from_key(private_key)
    sender_address   = account.address
    nonce            = w3.eth.get_transaction_count(sender_address)
    merkle_root_b32  = _hex_to_bytes32(merkle_root)

    tx = contract.functions.registerRecord(
        cid,
        Web3.to_checksum_address(receiver_address),
        session_id,
        merkle_root_b32,
    ).build_transaction({
        "from":     sender_address,
        "nonce":    nonce,
        "gas":      300_000,
        "gasPrice": w3.eth.gas_price,
    })

    signed  = w3.eth.account.sign_transaction(tx, private_key=private_key)
    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

    # Extract recordId from event log
    record_id = _extract_record_id_from_receipt(w3, contract, receipt)

    return {
        "tx_hash":      tx_hash.hex(),
        "record_id":    record_id,
        "block_number": receipt["blockNumber"],
        "gas_used":     receipt["gasUsed"],
    }


def get_record(w3: Web3, contract, record_id: int) -> dict:
    """
    Fetch a StegoRecord by its recordId.

    Returns
    -------
    dict: { record_id, cid, sender, receiver, session_id, merkle_root, timestamp, is_active }
    """
    rec = contract.functions.getRecord(record_id).call()
    return _parse_record_tuple(rec)


def get_record_by_cid(w3: Web3, contract, cid: str) -> dict:
    """Fetch a StegoRecord by IPFS CID."""
    rec = contract.functions.getRecordByCID(cid).call()
    return _parse_record_tuple(rec)


def verify_record(w3: Web3, contract, record_id: int, cid: str, merkle_root: str) -> bool:
    """Call the verifyRecord view function."""
    return contract.functions.verifyRecord(
        record_id, cid, _hex_to_bytes32(merkle_root)
    ).call()


def verify_merkle_proof_on_chain(
    w3: Web3,
    contract,
    proof: list,
    root: str,
    leaf: str,
) -> bool:
    """
    Call verifyMerkleProof on the contract.

    Parameters
    ----------
    proof : list of 0x-prefixed hex sibling hashes
    root  : 0x-prefixed bytes32 root hex string
    leaf  : 0x-prefixed bytes32 leaf hex string
    """
    proof_b32 = [_hex_to_bytes32(p) for p in proof]
    root_b32  = _hex_to_bytes32(root)
    leaf_b32  = _hex_to_bytes32(leaf)
    return contract.functions.verifyMerkleProof(proof_b32, root_b32, leaf_b32).call()


def get_contract_stats(w3: Web3, contract) -> dict:
    """Return { total_records, contract_owner }."""
    total, owner_addr = contract.functions.getContractStats().call()
    return {
        "total_records":   total,
        "contract_owner":  owner_addr,
    }


def revoke_record(w3: Web3, contract, private_key: str, record_id: int) -> dict:
    """
    Sign and send a revokeRecord transaction.

    Returns
    -------
    dict: { tx_hash, block_number, gas_used }
    """
    account = w3.eth.account.from_key(private_key)
    nonce   = w3.eth.get_transaction_count(account.address)

    tx = contract.functions.revokeRecord(record_id).build_transaction({
        "from":     account.address,
        "nonce":    nonce,
        "gas":      100_000,
        "gasPrice": w3.eth.gas_price,
    })

    signed  = w3.eth.account.sign_transaction(tx, private_key=private_key)
    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

    return {
        "tx_hash":      tx_hash.hex(),
        "block_number": receipt["blockNumber"],
        "gas_used":     receipt["gasUsed"],
    }


# ── Private helpers ───────────────────────────────────────────────────────────

def _keccak256_bytes(data: bytes) -> bytes:
    """Return raw 32-byte keccak256 digest of *data*."""
    return Web3.keccak(data)


def _hash_pair(a: bytes, b: bytes) -> bytes:
    """Hash a sorted pair (smaller first) with keccak256."""
    if a <= b:
        return Web3.keccak(a + b)
    else:
        return Web3.keccak(b + a)


def _hex_to_bytes32(hex_str: str) -> bytes:
    """Convert a 0x-prefixed hex string to 32 raw bytes."""
    stripped = hex_str.lstrip("0x")
    return bytes.fromhex(stripped.zfill(64))


def _parse_record_tuple(rec) -> dict:
    """Convert a contract tuple/namedtuple to a plain dict."""
    return {
        "record_id":   rec[0],
        "cid":         rec[1],
        "sender":      rec[2],
        "receiver":    rec[3],
        "session_id":  rec[4],
        "merkle_root": "0x" + rec[5].hex(),
        "timestamp":   rec[6],
        "is_active":   rec[7],
    }


def _extract_record_id_from_receipt(w3: Web3, contract, receipt) -> int:
    """Parse the RecordRegistered event to get the recordId."""
    try:
        logs = contract.events.RecordRegistered().process_receipt(receipt)
        if logs:
            return logs[0]["args"]["recordId"]
    except Exception:
        pass
    # Fallback: recordId = recordCount - 1 after the tx
    return contract.functions.recordCount().call() - 1
